(()=>{
  const U='https://joidkmccsncmfntzozoj.supabase.co',K='sb_publishable_90IXAfN8GYQ542aIjEdkhg_oeXIq__0';
  const $=s=>document.querySelector(s), token=()=>{try{return JSON.parse(localStorage.getItem('finca-fortuna-session')||'{}').access_token||''}catch{return''}};
  const api=async(p,o={})=>{const r=await fetch(U+p,{...o,headers:{apikey:K,Authorization:'Bearer '+token(),'Content-Type':'application/json',...(o.headers||{})}});if(!r.ok)throw Error(await r.text());const t=await r.text();return t?JSON.parse(t):null};
  document.head.insertAdjacentHTML('beforeend',`<style>#nf{position:fixed;right:14px;bottom:84px;z-index:90;background:#c99a3d;color:#173724;border:0;border-radius:30px;padding:13px 16px;font-weight:900}#np{display:none;position:fixed;inset:0;z-index:600;background:#10271dcc;place-items:center;padding:12px}#np.on{display:grid}.nb{background:#fffefa;width:min(760px,100%);max-height:94vh;overflow:auto;border-radius:16px;padding:20px}.nh{display:flex;justify-content:space-between}.nh button{border:0;background:none;font-size:25px}.ng{display:grid;grid-template-columns:1fr 1fr;gap:11px}.ng label{display:grid;gap:4px;font-size:12px;font-weight:800}.ng input,.ng select,.ng textarea{border:1px solid #cbd7ce;border-radius:8px;padding:9px}.na{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.na button{background:#28583a;color:#fff;border:0;border-radius:8px;padding:10px;font-weight:800}.na .gold{background:#c99a3d;color:#173724}#nm{margin-top:10px;font-weight:800;color:#28583a}@media(max-width:650px){.ng{grid-template-columns:1fr}}</style>`);
  document.body.insertAdjacentHTML('beforeend',`<button id="nf">📋 Asistencia y nómina</button><div id="np"><section class="nb"><div class="nh"><div><small>FINCA LA FORTUNA</small><h2>Asistencia y comprobantes</h2></div><button id="nx">×</button></div><p>Fijos: control diario y comprobante quincenal. Por día: comprobante por jornada.</p><div class="ng"><label>Obrero<select id="nw"></select></label><label>Tipo<select id="nt"><option>Fijo</option><option>Por día</option></select></label><label>Pago<select id="nq"><option>Quincenal</option><option>Diario</option></select></label><label>Fecha<input id="nd" type="date"></label><label>Asistencia<select id="ns"><option>Trabajó</option><option>Medio día</option><option>Falta justificada</option><option>Falta injustificada</option><option>Descanso</option></select></label><label>Trabajo<input id="nl" placeholder="Trabajo realizado"></label><label>Motivo o nota<textarea id="nr"></textarea></label><label>Desde<input id="ni" type="date"></label><label>Hasta<input id="no" type="date"></label></div><div class="na"><button id="nu">Guardar tipo</button><button id="nv">Registrar día</button><button id="nb" class="gold">🖨 Imprimir</button></div><div id="nm"></div></section></div>`);
  let W=[];const d=new Date(),iso=d.toISOString().slice(0,10),say=t=>$('#nm').textContent=t||'';$('#nd').value=iso;
  function period(){const y=d.getUTCFullYear(),m=String(d.getUTCMonth()+1).padStart(2,'0'),day=d.getUTCDate();$('#ni').value=`${y}-${m}-${day<=15?'01':'16'}`;$('#no').value=day<=15?`${y}-${m}-15`:new Date(Date.UTC(y,d.getUTCMonth()+1,0)).toISOString().slice(0,10)}period();
  const worker=()=>W.find(x=>String(x.id)===$('#nw').value);
  async function load(){W=await api('/rest/v1/farm_workers?select=*&active=eq.true&order=name');$('#nw').innerHTML='<option value="">Seleccionar</option>'+W.map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}
  $('#nf').onclick=async()=>{$('#np').classList.add('on');try{await load();say('')}catch{say('Ejecute primero la actualización SQL.')}};$('#nx').onclick=()=>$('#np').classList.remove('on');
  $('#nw').onchange=()=>{const w=worker();if(!w)return;$('#nt').value=w.worker_type||'Por día';$('#nq').value=w.payment_frequency||'Diario';if($('#nt').value==='Por día')$('#ni').value=$('#no').value=$('#nd').value;else period()};
  $('#nu').onclick=async()=>{const w=worker();if(!w)return say('Seleccione un obrero.');try{await api(`/rest/v1/farm_workers?id=eq.${w.id}`,{method:'PATCH',body:JSON.stringify({worker_type:$('#nt').value,payment_frequency:$('#nq').value})});w.worker_type=$('#nt').value;w.payment_frequency=$('#nq').value;say('Tipo de obrero guardado.')}catch{say('No se pudo guardar.')}};
  $('#nv').onclick=async()=>{const w=worker(),st=$('#ns').value;if(!w)return say('Seleccione un obrero.');const reason=$('#nr').value.trim();if(st.includes('Falta')&&!reason)return say('Escriba el motivo de la falta.');const days=st==='Trabajó'?1:st==='Medio día'?.5:0,amount=days*Number(w.daily_rate||0);try{await api('/rest/v1/farm_work_logs',{method:'POST',body:JSON.stringify({worker_id:w.id,work_date:$('#nd').value,work_type:'Jornal',days,rate_snapshot:Number(w.daily_rate||0),description:$('#nl').value,amount,attendance_status:st,absence_reason:reason})});say(`Día guardado: ${amount.toLocaleString('es-CU')} CUP`)}catch{say('No se pudo registrar el día.')}};
  $('#nb').onclick=async()=>{const w=worker(),a=$('#ni').value,z=$('#no').value;if(!w||!a||!z)return say('Seleccione obrero y fechas.');try{const [L,P]=await Promise.all([api(`/rest/v1/farm_work_logs?select=*&worker_id=eq.${w.id}&work_date=gte.${a}&work_date=lte.${z}&order=work_date`),api(`/rest/v1/farm_payments?select=*&worker_id=eq.${w.id}&payment_date=gte.${a}&payment_date=lte.${z}`)]),earned=L.reduce((s,x)=>s+Number(x.amount),0),paid=P.reduce((s,x)=>s+Number(x.amount),0),rows=L.map(x=>`<tr><td>${x.work_date}</td><td>${x.attendance_status||'Trabajó'}</td><td>${x.description||x.absence_reason||'-'}</td><td>${x.days}</td><td>${Number(x.amount).toLocaleString('es-CU')}</td></tr>`).join(''),p=open('','_blank');p.document.write(`<!doctype html><html><head><meta charset=utf-8><style>body{font-family:Arial}h1,h2{text-align:center}table{width:100%;border-collapse:collapse}td,th{border:1px solid #999;padding:7px}.sig{display:flex;justify-content:space-between;margin-top:60px}.sig span{border-top:1px solid;width:42%;text-align:center}</style></head><body><h1>Finca La Fortuna</h1><h2>${(w.worker_type||'Por día')==='Fijo'?'Comprobante quincenal':'Comprobante por día'}</h2><p><b>Obrero:</b> ${w.name}</p><p><b>Período:</b> ${a} al ${z}</p><table><tr><th>Fecha</th><th>Asistencia</th><th>Trabajo o motivo</th><th>Días</th><th>CUP</th></tr>${rows}</table><h3>Total ganado: ${earned.toLocaleString('es-CU')} CUP</h3><p>Pagado: ${paid.toLocaleString('es-CU')} CUP · Saldo: ${(earned-paid).toLocaleString('es-CU')} CUP</p><div class=sig><span>Firma del obrero</span><span>Firma del responsable</span></div><script>setTimeout(()=>print(),300)<\/script></body></html>`);p.document.close()}catch{say('No se pudo imprimir.')}};
})();
